### ISSUE TITLE
use it along with CasparCG official Client

### ISSUE THREAD

**Issue by deedos** [SublanTV/CasparsPlayoutClient#29]
Hi. 

If I open both softwares, the last one opened, crash the first. Is it sometihing known ?
thanks in advance

**Comment by mcdikki** [comment]
Hi,

this is a problem with the OSC port. The first program opens the socket and the second crashs trying it.
(Which shows that both, me and the ccg devs are a little slacky checking for exceptions. Shame on us :-) )

I already fixed this is the current code base. 
You can solve it by changing the OSC port of the client and manually add the pc its running on to your ccg config.

**Comment by deedos** [comment]
So much thanks for the info!


2015-07-29 16:31 GMT-03:00 Christopher <notifications@github.com>:

> Hi,
>
> this is a problem with the OSC port. The first program opens the socket
> and the second crashs trying it.
> (Which shows that both, me and the ccg devs are a little slacky checking
> for exceptions. Shame on us :-) )
>
> I already fixed this is the current code base.
> You can solve it by changing the OSC port of the client and manually add
> the pc its running on to your ccg config.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublanTV/CasparsPlayoutClient/issues/29#issuecomment-126068661>
> .
>



-- 
Daniel Roviriego
(21) 35920701
(21) 99561654
