### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by deedos** [SublanTV/CasparsPlayoutClient#30]
Windows 7 professional clesan install:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	CasparsPlayoutClient.exe
  Application Version:	0.1.1.0
  Application Timestamp:	54ea907f
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.18247
  Fault Module Timestamp:	521eaf24
  Exception Code:	c00000fd
  Exception Offset:	000000000006af5e
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	fde4
  Additional Information 2:	fde4ea0a2b06aa7f291075b171498126
  Additional Information 3:	80ae
  Additional Information 4:	80ae86f4515a72176cd87e67e3bdfd30

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

thanks in advance

**Comment by mcdikki** [comment]
Hi and thx for the bug report.
Unfortunately this information does not help me a lot.

Could you explain the circumstances in which the app has crashed? 
Is it reproducible and if yes, how?

And the error messages indicates that the problem my be out of my scope as the crash happend in ntdll.dll, which is a system library and not part of my code.

cheers

**Comment by mcdikki** [comment]
Since there is no response on this, I'll close this issue. Fell free to reopen it if necessary.
